apiVersion: v1
kind: ConfigMap
metadata:
  name: application-config
  namespace: transporte
#common configuration shared between all applications
data:
  application.yml: |-
    configserver:
      name:  JHipster Registry
      status: Connected to the JHipster Registry running in Kubernetes
    eureka:
      client:
        initial-instance-info-replication-interval-seconds: 15
        instance-info-replication-interval-seconds: 15
        registry-fetch-interval-seconds: 15
        fetch-registry: true
        register-with-eureka: true
        eureka-service-url-poll-interval-seconds: 15
      instance:
        lease-renewal-interval-in-seconds: 10
        registry-default-open-for-traffic-count: 0
    jhipster:
      security:
        authentication:
          jwt:
            base64-secret: NDk0MTU3NjM3N2Y1Zjk1YjVjYzI5NmE5OGY0YzJiZjIyMTQxMzY2MDNjODI5N2U4OGRjODMwMDZiZjIzYmIxMjY5MTRiNjI2NzYzYjgwN2MzMzYxZDBiM2ZhY2IwMjA2YWFiOTQ4ZTE2Y2Y1MzZhODI5NmRmODgwNDgwMGM1ZTI=
  # app specific configuration
  jhipster-registry.yml: |-
    eureka:
      client:
        service-url:
          defaultZone: http://admin:${spring.security.user.password}@jhipster-registry-0.jhipster-registry.transporte.svc.cluster.local:8761/eureka/,http://admin:${spring.security.user.password}@jhipster-registry-1.jhipster-registry.transporte.svc.cluster.local:8761/eureka/
