apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: genesisoft/transporte
      context: ../transporte-app
      jib: {}
  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_NAME}}:latest'
deploy:
  kustomize: {}
