export enum AttachmentType {
  SUPPLIERS = 'SUPPLIERS',

  VEHICLE_CONTROL = 'VEHICLE_CONTROL',

  CUSTOMERS = 'CUSTOMERS',

  HOUSING = 'HOUSING',

  QUOTATION = 'QUOTATION',

  EMPLOYEE = 'EMPLOYEE',
}
