export enum InspectionPositions {
  FRONT = 'FRONT',

  REAR = 'REAR',

  LEFT_DOOR_FRONT = 'LEFT_DOOR_FRONT',

  LEFT_DOOR_REAR = 'LEFT_DOOR_REAR',

  RIGHT_DOOR_FRONT = 'RIGHT_DOOR_FRONT',

  RIGHT_DOOR_REAR = 'RIGHT_DOOR_REAR',

  LEFT_SIDE = 'LEFT_SIDE',

  RIGHT_SIDE = 'RIGHT_SIDE',
}
